### ISSUE TITLE
the"Tracker v2.1.9.8" installation fail.

### ISSUE THREAD

**Issue by TzuHwang** [Neurotar/locomotion-tracking-software#30]
the program installation fail, the screen shows error 1324. I had try win7 and win10 to install this program, the path was showed in picture. p.s. the default path doesn't work. 
![Capture](https://user-images.githubusercontent.com/49851854/56481405-6a032e00-64f1-11e9-89ca-c67f7d0e1512.JPG)

![Capture1](https://user-images.githubusercontent.com/49851854/56481924-0f1f0600-64f4-11e9-8a61-7285721fc83a.JPG)

**Comment by dmitriy-t** [comment]
Thank you very much for detailed bug report!
We will try to release an updated version asap.

**Comment by dmitriy-t** [comment]
Fixed in the version 2.1.9.10.
