### ISSUE TITLE
I/O 2 TTL upon start and stop of recording

### ISSUE THREAD

**Issue by IljaPilja** [Neurotar/locomotion-tracking-software#35]
Hi,
I read on one of the closed issues that I/O 2 is used to output a TTL at onset and offset of recording. Not only does this TTL show on I/O 2 but also appears on I/O 1 and I/O 4, the latter two I use to indicate whether the mouse has entered a specific zone and is in any other zone. So this will mess up my air-puff stimulus because now, no matter where the mouse is at the start of the recording the I/O 2 signal (appearing on I/O 1) will activate the air-puffer. How can I contain the onset/offset signal to only appear on I/O 2?

Ilja

**Comment by dmitriy-t** [comment]
Hi Ilja,

Which version of the software you are using? And if this is any of 2.2.x versions, could you please make a settings file export (via Settings -> Save Settings) and send this file to me?

Kind regards,
Dmytro

**Comment by IljaPilja** [comment]
Ok, I think the problem that I'm having has nothing to do with the software but with the I/O connector. I'm using I/O 1 and I/O 4 as well as the I/O 2 for the TTL indicating the onset and offset of the recording. Placing the two wires into the I/O 1 and 4 works fine but the I/O 2 simply does not hold the wires, there is no grip on them. I thought it seemed a good idea to sauter a stiffer copper wire to the wires so that I could make them stick, but this only caused the problem that I described, namely that the signal appears on all I/O outputs. I believe the green connector is broken, as it is unable to grip the wires. Is there a way to buy only this green connector? Or maybe you have another solution to my problem.

Thanks,
Ilja

**Comment by IljaPilja** [comment]
Sorry about that, I think I did get the wires into the I/O 2 in the right manner but unfortunately, the signal does appear on all my three outputs. I'll send the settings file as you requested.

Ilja

**Comment by dmitriy-t** [comment]
Hi Ilja,

Thank you for investigating the issue. 

Concerning green connector block (just in case).  You can find one here: https://www.digikey.com/product-detail/en/phoenix-contact/1790124/277-8778-ND/2743738

Concerning wrong I/O activation: please send settings file to mhc-support@neurotar.com (add something about issue #35 into subject line), or just attach file to your post here.

Kind regards,
Dmytro
