### ISSUE TITLE
Electrical noise using silicon probe

### ISSUE THREAD

**Issue by IljaPilja** [Neurotar/locomotion-tracking-software#36]
Hi,
I have a linear 16 electrode silicon probe implanted in S1 of my mouse and I would like to record this activity in the Neurotar device. If I simply record the activity while the mouse is freely moving in a small arena, the noise level is within the normal range. However, once I head-retrain the mouse in the Neurotar set-up, the noise levels are bad. I've tried to determine where the noise (60 Hz) comes from but I have till now been unsuccessful. Is there some trick that I have not thought of to reduce this noise? 

Any advice would be greatly appreciated.

Ilja

**Comment by dmitriy-t** [comment]
Hi Ilja,

According to our own measurements as well as our users with ephys rigs, 
device itself makes a weak noise at 100 Hz. This noise level is quite 
small and noticeable only under certain conditions. This noise (even if 
it is noticeable) can be easily eliminated by device' lid grounding.


The more complicated thing is 60 Hz (or 50 Hz in Europe) noise.

The main sources of that are:

  * Room illumination (cathode lamps are especially bad with that).
  * PC where Tracker device is connected.
      o We've noticed, that if laptop is not connected to mains, amount
        of 60 Hz noise can increase more than 10-fold in some cases.
      o Some laptops can be also do good job on battery, but some are
        bad even when running from electrical socket.
      o Your PC/laptop can be OK, but power cable or electrical socket
        don't. If power cable of your PC/laptop has a grounding pin,
        make sure, that electrical socket also have one (and it is
        functional).
  * Finally, noise can come from electrical network, from some other
    device which is not even in your room, and by some reason your
    PC/laptop can't filter that.


What to do:

  * Play with room illumination.
  * Try to plug/unplug your computer from mains (if this is a laptop).
  *   Try different electrical socket (better on other side of the room).
  *   Check that USB cable from the computer to the device is not
    touching anything like power cables on it's way to the Tracker device.
  *   Try to ground the lid of the device.


Hope this helps.

Kind regards,
Dmytro
