### ISSUE TITLE
Sampling rate increase

### ISSUE THREAD

**Issue by IljaPilja** [Neurotar/locomotion-tracking-software#37]
Hi,
I noticed upon analyzing the generated *.tdms file that the sampling rate is at 100 Hz. My probe recordings are at 20 kHz and I was wondering why the rather low sampling rate is used by the Neurotar device and if this can be changed?

Ilja

**Comment by dmitriy-t** [comment]
Hi,

Sorry for delay with answer. 

Concernig sampling rate considerations and why it was set to 100 Hz: 
"Events" in mouse running activity much slower and longer than in the neurons activity for the same animal. Length of the neuronal spike event is around 5 ms (i.e. ~100 readouts at 20 kHz). In most cases, any noticeable change of the track shape (e.g. turn) takes something around a second. So, we practically have the same ~100 readouts per event which is enough to recreate accurate trajectory.
There is no way to increase a sampling rate above 100 Hz from the software at the moment. 
Hope this answers your question.

Kind regards,
Dmytro
